In [1]:
import pandas as pd
from pandas import DataFrame

In [2]:
toyota_data = pd.read_csv('toyota_sales_data.csv')

In [3]:
toyota_data

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
...,...,...,...,...,...,...,...
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed
4998,4999,10,2024-11-21,Corolla,22654.59,NaN,Completed
4999,5000,13,2024-11-21,Tundra,44525.85,NaN,Cancelled

In [4]:
toyota_data.shape

(5000, 7)

In [8]:
chunk_size = 100

In [9]:
toyota_chunk_reader = pd.read_csv(
    'toyota_sales_data.csv',
    chunksize=chunk_size
                  )

In [10]:
type(toyota_chunk_reader)

pandas.io.parsers.readers.TextFileReader

In [11]:
type(toyota_data)

pandas.core.frame.DataFrame

In [12]:
for toyota_chunk in toyota_chunk_reader:
    print(toyota_chunk)

    sale_id  sale_rep_id   sale_date   car_model  sale_amount  commission_pct  \
0         1           16  2024-11-18      Tundra     44496.88            0.05
1         2           11  2024-11-08      Tacoma     34824.72             NaN
2         3            5  2024-11-03     Corolla     20275.08             NaN
3         4           20  2024-11-06     Corolla     20068.93             NaN
4         5            1  2024-11-26      Tundra     49811.99            0.03
..      ...          ...         ...         ...          ...             ...
95       96           16  2024-11-17  Highlander     44498.46            0.03
96       97            6  2024-11-23  Highlander     41994.79             NaN
97       98            1  2024-11-07      Tacoma     31378.09            0.02
98       99            1  2024-11-04      Tundra     39879.41            0.02
99      100           16  2024-11-20       Camry     25962.56            0.02

   sale_status
0    Completed
1      Pending
2    Completed
3    Completed
4    Completed
..         ...
95   Completed
96   Completed
97   Completed
98   Completed
99   Completed

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
100      101            7  2024-11-13        RAV4     32219.86
101      102            2  2024-11-01      Tacoma     36531.02
102      103            6  2024-11-04  Highlander     39423.27
103      104           13  2024-11-01  Highlander     38543.89
104      105            2  2024-11-12      Tacoma     34122.47
..       ...          ...         ...         ...          ...
195      196           11  2024-11-09        RAV4     29093.11
196      197           17  2024-11-08        RAV4     28611.77
197      198            3  2024-11-09       Camry     25062.95
198      199            6  2024-11-17     Corolla     23423.36
199      200           13  2024-11-24     Corolla     24257.34

     commission_pct sale_status
100            0.03     Pending
101             NaN   Completed
102            0.02   Cancelled
103            0.05   Completed
104             NaN   Completed
..              ...         ...
195             NaN   Completed
196            0.03   Completed
197             NaN   Completed
198            0.02   Completed
199            0.02     Pending

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
200      201            9  2024-11-10       Camry     26339.37
201      202           20  2024-11-11  Highlander     40517.24
202      203           19  2024-11-18        RAV4     34245.12
203      204            5  2024-11-01        RAV4     34529.56
204      205           13  2024-11-21        RAV4     34392.53
..       ...          ...         ...         ...          ...
295      296           10  2024-11-08       Camry     28082.83
296      297            7  2024-11-07     Corolla     20673.95
297      298           14  2024-11-17      Tundra     39871.64
298      299           18  2024-11-26      Tacoma     37510.47
299      300           20  2024-11-13      Tundra     38715.73

     commission_pct sale_status
200             NaN   Cancelled
201            0.03   Completed
202            0.03   Completed
203            0.03   Completed
204            0.05     Pending
..              ...         ...
295             NaN   Completed
296            0.03   Completed
297            0.03   Completed
298            0.05   Completed
299            0.03     Pending

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
300      301            2  2024-11-15       Camry     26249.79
301      302           18  2024-11-01      Tundra     46279.17
302      303           15  2024-11-17     Corolla     20934.30
303      304            9  2024-11-17        RAV4     28249.37
304      305           16  2024-11-14        RAV4     32867.17
..       ...          ...         ...         ...          ...
395      396           11  2024-11-18  Highlander     36156.36
396      397            6  2024-11-04     Corolla     21351.34
397      398            3  2024-11-24      Tundra     48565.64
398      399           15  2024-11-12  Highlander     42981.01
399      400           17  2024-11-18     Corolla     21446.28

     commission_pct sale_status
300             NaN   Cancelled
301            0.03   Completed
302             NaN   Completed
303             NaN   Completed
304            0.05   Completed
..              ...         ...
395            0.03   Cancelled
396             NaN     Pending
397            0.03   Completed
398             NaN   Completed
399             NaN   Completed

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
400      401           20  2024-11-08      Tacoma     37829.94
401      402           15  2024-11-21     Corolla     22046.96
402      403            2  2024-11-03  Highlander     43701.27
403      404            5  2024-11-12     Corolla     20220.42
404      405            4  2024-11-11        RAV4     34218.51
..       ...          ...         ...         ...          ...
495      496           18  2024-11-10      Tundra     43326.45
496      497           14  2024-11-17        RAV4     33267.99
497      498            9  2024-11-11     Corolla     22295.37
498      499           15  2024-11-21        RAV4     28000.64
499      500            7  2024-11-04      Tacoma     31488.11

     commission_pct sale_status
400            0.03   Completed
401            0.02     Pending
402            0.05   Completed
403            0.05     Pending
404            0.05   Completed
..              ...         ...
495             NaN     Pending
496            0.03   Completed
497             NaN     Pending
498            0.02   Completed
499             NaN   Cancelled

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
500      501           16  2024-11-11      Tacoma     33515.35
501      502            2  2024-11-09  Highlander     35071.08
502      503            8  2024-11-01        RAV4     34498.34
503      504            2  2024-11-15      Tacoma     34479.83
504      505           11  2024-11-11      Tacoma     39145.84
..       ...          ...         ...         ...          ...
595      596            2  2024-11-11      Tacoma     36247.43
596      597           15  2024-11-30     Corolla     21546.42
597      598           11  2024-11-16     Corolla     23844.93
598      599           19  2024-11-03  Highlander     39474.30
599      600            6  2024-11-04       Camry     26371.67

     commission_pct sale_status
500            0.03   Completed
501            0.05   Completed
502            0.05   Completed
503             NaN   Completed
504            0.03   Completed
..              ...         ...
595             NaN     Pending
596             NaN   Completed
597             NaN   Cancelled
598            0.02   Completed
599            0.02     Pending

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
600      601            4  2024-11-28     Corolla     24866.00
601      602           13  2024-11-19        RAV4     33439.65
602      603            5  2024-11-05  Highlander     42125.82
603      604           20  2024-11-06  Highlander     42302.20
604      605           14  2024-11-26     Corolla     23486.71
..       ...          ...         ...         ...          ...
695      696            8  2024-11-02      Tundra     35968.92
696      697            2  2024-11-04      Tacoma     39907.71
697      698           18  2024-11-05        RAV4     33067.79
698      699            1  2024-11-10     Corolla     22800.87
699      700            9  2024-11-20       Camry     29206.75

     commission_pct sale_status
600            0.05   Completed
601            0.05   Completed
602            0.05   Completed
603            0.05   Completed
604             NaN     Pending
..              ...         ...
695            0.05   Completed
696            0.05   Completed
697            0.05   Completed
698            0.03     Pending
699            0.05   Completed

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
700      701           11  2024-11-06  Highlander     44864.78
701      702           12  2024-11-10        RAV4     30350.62
702      703           20  2024-11-10      Tundra     37167.28
703      704           11  2024-11-10        RAV4     30375.58
704      705           18  2024-11-06     Corolla     22956.19
..       ...          ...         ...         ...          ...
795      796            7  2024-11-01       Camry     25589.58
796      797           13  2024-11-21     Corolla     21818.10
797      798           19  2024-11-15  Highlander     35617.00
798      799           16  2024-11-27        RAV4     33852.90
799      800           15  2024-11-18  Highlander     40808.16

     commission_pct sale_status
700             NaN   Completed
701            0.02   Completed
702             NaN   Completed
703             NaN     Pending
704            0.03   Completed
..              ...         ...
795             NaN     Pending
796            0.05     Pending
797             NaN   Completed
798            0.05   Completed
799            0.02   Completed

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
800      801           18  2024-11-19      Tundra     49020.28
801      802           20  2024-11-18       Camry     29267.04
802      803            1  2024-11-09      Tacoma     36407.58
803      804            6  2024-11-25  Highlander     44077.69
804      805           13  2024-11-11  Highlander     39608.26
..       ...          ...         ...         ...          ...
895      896           14  2024-11-04  Highlander     37330.04
896      897            1  2024-11-14      Tacoma     34588.41
897      898           18  2024-11-30      Tacoma     38174.42
898      899            9  2024-11-04      Tundra     40678.45
899      900            3  2024-11-12       Camry     28054.12

     commission_pct sale_status
800            0.03   Completed
801            0.03     Pending
802            0.03     Pending
803             NaN     Pending
804             NaN   Completed
..              ...         ...
895            0.02   Completed
896            0.03     Pending
897            0.05     Pending
898            0.03   Completed
899            0.03     Pending

[100 rows x 7 columns]
     sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
900      901            2  2024-11-28     Camry     25700.31             NaN
901      902           16  2024-11-05   Corolla     23437.32            0.05
902      903           15  2024-11-27    Tacoma     31365.19            0.02
903      904           10  2024-11-04    Tundra     43019.93            0.03
904      905            9  2024-11-12   Corolla     23309.34            0.02
..       ...          ...         ...       ...          ...             ...
995      996           13  2024-11-01   Corolla     21044.21            0.03
996      997           16  2024-11-03      RAV4     29658.52            0.03
997      998            5  2024-11-23    Tacoma     39531.12            0.02
998      999           13  2024-11-05   Corolla     21786.00             NaN
999     1000           14  2024-11-06     Camry     25376.67             NaN

    sale_status
900     Pending
901   Completed
902   Completed
903   Cancelled
904   Completed
..          ...
995   Cancelled
996   Completed
997   Completed
998     Pending
999   Completed

[100 rows x 7 columns]
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1000     1001           20  2024-11-08       Camry     27774.90
1001     1002            6  2024-11-02      Tundra     49823.29
1002     1003            7  2024-11-06  Highlander     36224.40
1003     1004            6  2024-11-21      Tundra     43133.05
1004     1005            1  2024-11-28       Camry     28852.21
...       ...          ...         ...         ...          ...
1095     1096            3  2024-11-06       Camry     28503.05
1096     1097           19  2024-11-26       Camry     29268.39
1097     1098           10  2024-11-10     Corolla     20257.51
1098     1099           20  2024-11-26     Corolla     20102.73
1099     1100            5  2024-11-10     Corolla     20590.19

      commission_pct sale_status
1000            0.05   Completed
1001            0.05   Completed
1002             NaN   Completed
1003            0.02   Completed
1004            0.05     Pending
...              ...         ...
1095            0.03   Completed
1096             NaN     Pending
1097             NaN   Completed
1098            0.03   Completed
1099            0.05     Pending

[100 rows x 7 columns]
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1100     1101            3  2024-11-12       Camry     28573.57
1101     1102            8  2024-11-10        RAV4     31084.65
1102     1103           12  2024-11-17      Tundra     45353.37
1103     1104            2  2024-11-07      Tundra     35679.36
1104     1105           10  2024-11-10      Tundra     36296.36
...       ...          ...         ...         ...          ...
1195     1196            2  2024-11-29     Corolla     24429.20
1196     1197           12  2024-11-24        RAV4     29543.07
1197     1198           17  2024-11-11     Corolla     20901.18
1198     1199            9  2024-11-01      Tundra     38460.48
1199     1200            9  2024-11-08  Highlander     44680.16

      commission_pct sale_status
1100             NaN   Completed
1101            0.02   Completed
1102            0.03   Completed
1103            0.02     Pending
1104            0.05   Completed
...              ...         ...
1195             NaN   Completed
1196            0.03   Completed
1197            0.03   Cancelled
1198            0.03     Pending
1199            0.02   Completed

[100 rows x 7 columns]
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1200     1201            4  2024-11-28     Corolla     20342.27
1201     1202           15  2024-11-20       Camry     25486.31
1202     1203            3  2024-11-06      Tacoma     35010.72
1203     1204            7  2024-11-15       Camry     25794.73
1204     1205           12  2024-11-19       Camry     29471.63
...       ...          ...         ...         ...          ...
1295     1296           19  2024-11-26       Camry     25083.80
1296     1297           20  2024-11-05        RAV4     33020.35
1297     1298           16  2024-11-07       Camry     27709.55
1298     1299           12  2024-11-10  Highlander     41933.71
1299     1300           16  2024-11-23  Highlander     38189.24

      commission_pct sale_status
1200            0.03   Completed
1201            0.05   Completed
1202            0.03   Completed
1203            0.05   Completed
1204            0.03   Completed
...              ...         ...
1295             NaN   Completed
1296             NaN   Completed
1297             NaN   Completed
1298            0.05   Completed
1299             NaN   Completed

[100 rows x 7 columns]
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1300     1301           12  2024-11-21      Tundra     35114.87
1301     1302           17  2024-11-26        RAV4     31323.50
1302     1303            6  2024-11-08  Highlander     39615.09
1303     1304            2  2024-11-15        RAV4     33358.30
1304     1305           12  2024-11-06      Tacoma     38039.67
...       ...          ...         ...         ...          ...
1395     1396            5  2024-11-03  Highlander     36675.72
1396     1397            2  2024-11-21  Highlander     41598.88
1397     1398            4  2024-11-22     Corolla     23893.60
1398     1399            8  2024-11-28        RAV4     30440.13
1399     1400            7  2024-11-17       Camry     26530.86

      commission_pct sale_status
1300             NaN   Completed
1301            0.02   Completed
1302            0.03   Completed
1303            0.03     Pending
1304            0.02   Completed
...              ...         ...
1395            0.05   Completed
1396            0.03   Completed
1397             NaN     Pending
1398            0.05     Pending
1399             NaN   Completed

[100 rows x 7 columns]
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1400     1401           11  2024-11-01  Highlander     40400.17
1401     1402           16  2024-11-01       Camry     25528.28
1402     1403           11  2024-11-20     Corolla     20705.85
1403     1404            5  2024-11-07      Tundra     40194.56
1404     1405            1  2024-11-24  Highlander     35642.75
...       ...          ...         ...         ...          ...
1495     1496           18  2024-11-05        RAV4     34413.45
1496     1497           13  2024-11-04      Tacoma     33591.93
1497     1498           11  2024-11-18     Corolla     22247.66
1498     1499           13  2024-11-05      Tacoma     36941.92
1499     1500            8  2024-11-24      Tacoma     33366.99

      commission_pct sale_status
1400            0.03   Completed
1401            0.05   Completed
1402            0.03   Completed
1403            0.05     Pending
1404            0.05   Completed
...              ...         ...
1495            0.02     Pending
1496            0.02   Completed
1497             NaN     Pending
1498            0.05     Pending
1499            0.03     Pending

[100 rows x 7 columns]
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1500     1501           18  2024-11-05      Tundra     41381.86
1501     1502            1  2024-11-18        RAV4     27290.01
1502     1503            3  2024-11-29  Highlander     41047.98
1503     1504           10  2024-11-30      Tundra     45743.25
1504     1505            2  2024-11-06      Tacoma     37943.78
...       ...          ...         ...         ...          ...
1595     1596            6  2024-11-22  Highlander     37764.86
1596     1597           16  2024-11-27     Corolla     22309.78
1597     1598           13  2024-11-10     Corolla     21994.54
1598     1599           10  2024-11-27     Corolla     23687.98
1599     1600           19  2024-11-18      Tundra     48775.41

      commission_pct sale_status
1500            0.02   Completed
1501            0.05   Completed
1502            0.05     Pending
1503            0.02   Completed
1504            0.02   Completed
...              ...         ...
1595            0.02   Completed
1596            0.02   Cancelled
1597            0.03     Pending
1598             NaN     Pending
1599             NaN     Pending

[100 rows x 7 columns]
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1600     1601            5  2024-11-13      Tundra     41455.14
1601     1602            9  2024-11-12      Tundra     39578.10
1602     1603            4  2024-11-27     Corolla     20685.84
1603     1604            7  2024-11-18      Tundra     48682.36
1604     1605           16  2024-11-30      Tundra     43522.74
...       ...          ...         ...         ...          ...
1695     1696            1  2024-11-17  Highlander     37956.95
1696     1697           13  2024-11-01      Tundra     37760.79
1697     1698           10  2024-11-17     Corolla     21400.22
1698     1699            5  2024-11-19  Highlander     42992.91
1699     1700           17  2024-11-22        RAV4     32270.73

      commission_pct sale_status
1600            0.05   Completed
1601            0.02     Pending
1602            0.05   Completed
1603            0.02   Completed
1604             NaN   Completed
...              ...         ...
1695            0.03   Completed
1696            0.03   Completed
1697            0.03   Completed
1698             NaN   Completed
1699            0.02     Pending

[100 rows x 7 columns]

In [13]:
for toyota_chunk in toyota_chunk_reader:
    print(toyota_chunk.head())

How to Apply Transformations on DataFrame